default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  password: <%= ENV.fetch('DB_PASS', '') %>
  username: <%= ENV.fetch('DB_USER', '') %>
development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'recipes_api_development') %>
test:
  <<: *default
  database: recipes_api_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'recipes_api') %>
